name: nogo_timer_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:

  # 日付フォーマットパッケージ
  intl: 0.17.0-nullsafety.2
  # 振動パッケージ
  vibration: ^1.7.3
  #設定保存用パッケージ
  shared_preferences: ^2.1.1
  #アラーム用
  flutter_ringtone_player: ^3.2.0
  #メールソフト起動、外部URL開く用パッケージ
  url_launcher: ^6.1.11
  #端末情報取得用
  device_info_plus: ^8.2.2
  #折りたたみウィジェット
  expandable: ^5.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #アイコン作成用
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'
  adaptive_icon_foreground: 'assets/images/icon_adaptive_foreground.png'
  adaptive_icon_background: "#f7e3af"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/ringtone.mp3
    - assets/images/main_img.png
    - assets/images/mark_nice.jpg
    - assets/images/mark_enough.jpg
    - assets/images/mark_good.jpg
    - assets/images/stamps/1_stamp_aka.png
    - assets/images/stamps/1_hana_01.png
    - assets/images/stamps/1_hana_02.png
    - assets/images/stamps/1_hana_03.png
    - assets/images/stamps/1_sun.png
    - assets/images/stamps/1_moon.png
    - assets/images/stamps/1_hana_11.png
    - assets/images/stamps/1_hana_12.png
    - assets/images/stamps/1_hana_13.png
    - assets/images/stamps/1_hana_14.png
    - assets/images/stamps/1_hana_15.png
    - assets/images/stamps/1_gift_11.png
    - assets/images/stamps/1_gift_12.png
    - assets/images/stamps/1_gift_13.png
    - assets/images/stamps/1_gift_14.png
    - assets/images/stamps/1_cupcake_11.png
    - assets/images/stamps/1_cupcake_12.png
    - assets/images/stamps/1_cupcake_13.png
    - assets/images/stamps/1_cupcake_14.png
    - assets/images/stamps/1_cupcake_15.png
    - assets/images/stamps/1_cupcake_16.png
    - assets/images/stamps/1_fruit_11.png
    - assets/images/stamps/1_fruit_12.png
    - assets/images/stamps/1_fruit_13.png
    - assets/images/stamps/1_fruit_14.png
    - assets/images/stamps/1_fruit_15.png
    - assets/images/stamps/1_fruit_16.png
    - assets/images/stamps/1_vegetable_01.png
    - assets/images/stamps/1_vegetable_02.png
    - assets/images/stamps/1_vegetable_03.png
    - assets/images/stamps/1_vegetable_04.png
    - assets/images/stamps/1_sweets_01.png
    - assets/images/stamps/1_sweets_02.png
    - assets/images/stamps/1_sweets_03.png
    - assets/images/stamps/1_sweets_04.png
    - assets/images/stamps/1_sweets_05.png
    - assets/images/stamps/1_sweets_06.png
    - assets/images/stamps/1_sweets_07.png
    - assets/images/stamps/1_cars_01.png
    - assets/images/stamps/1_cars_01.png
    - assets/images/stamps/1_cars_02.png
    - assets/images/stamps/1_cars_03.png
    - assets/images/stamps/1_cars_04.png
    - assets/images/stamps/1_cars_05.png
    - assets/images/stamps/1_cars_06.png
    - assets/images/stamps/1_bird_01.png
    - assets/images/stamps/1_bird_02.png
    - assets/images/stamps/1_bird_03.png
    - assets/images/stamps/1_bird_04.png
    - assets/images/stamps/1_bird_05.png
    - assets/images/stamps/1_bird_06.png
    - assets/images/stamps/2_cloud_and_moon.png
    - assets/images/stamps/3_stamp_aka.png
    - assets/images/stamps/3_cloud.png
    - assets/images/stamps/3_rain.png
    - assets/images/unspecified.png
    - assets/images/unspecifiedStamp.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
